#!/bin/bash

POKEMONS=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
OUTPUT_DIR="pokemon_data"
mkdir -p "$OUTPUT_DIR"


MAX_RETRIES=3

for pokemon in "${POKEMONS[@]}"; do
    echo "Fetching data for $pokemon..."

    URL="https://pokeapi.co/api/v2/pokemon/$pokemon"
    OUTPUT_FILE="$OUTPUT_DIR/$pokemon.json"

    attempt=1
    success=0

    while [ $attempt -le $MAX_RETRIES ]; do
        curl -s "$URL" -o "$OUTPUT_FILE"

        if [ -s "$OUTPUT_FILE" ]; then
            echo "Saved data to $OUTPUT_FILE ✅"
            success=1
            break
        else
            echo "Attempt $attempt failed for $pokemon"
            rm -f "$OUTPUT_FILE"
            attempt=$((attempt + 1))
            sleep 2
        fi
    done

    if [ $success -eq 0 ]; then
        echo "Failed to fetch data for $pokemon after $MAX_RETRIES attempts." >> error_log.txt
    fi

    sleep 2
done

