#!/bin/bash

NAME=$(jq -r '.name' data.json | sed 's/.*/\u&/')
HEIGHT=$(jq -r '.height' data.json)
WEIGHT=$(jq -r '.weight' data.json)
TYPE=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

HEIGHT_M=$(awk "BEGIN {printf \"%.1f\", $HEIGHT/10}")
WEIGHT_KG=$(awk "BEGIN {printf \"%.1f\", $WEIGHT/10}")

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."

